hydra:
  run: 
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/${hydra.job.name}_${description}

description: Resnet+LSTM

csi: csi_sign_language
transform: torchvision.transforms
T: torchvision.transforms
CT: csi_sign_language.data.transforms

seed: 3407
phoenix14_root: /home/jingyan/Documents/sign_language_rgb/preprocessed/ph14_lmdb
device: cuda
verbose: True
epoch: 40
#-1 when we don want message out
message_interval: 50
non_block: True
pin_memory: True
num_workers: 6

#if continuos read model as previous configured
is_resume: False
checkpoint: /home/jingyan/Documents/sign_language_rgb/outputs/staged/00-39-07

model:
  _target_: ${csi}.models.model.SLRModel
  loss_weight: [1., 1., 25.]
  loss_temp: 8
  backbone: 
    _target_: ${csi}.models.backbones.resnetbased.ResnetLSTM
    n_class: 1296
    n_layers: 2

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0.0001

lr_scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR
  lr_lambda: 
    _target_: ${csi}.engines.lr_scheduler.WarmUpLr
    initial_lambda: 0.001
    warm_up_rounds: 0
    decay_factor: 0.8

trainner:
  _target_: ${csi}.engines.trainner.Trainner
  device: ${device}
  message_interval: ${message_interval}

inferencer:
  _target_: ${csi}.engines.inferencer.Inferencer
  device: ${device}

data:
  subset: multisigner
  collate_fn: 
    _target_: ${csi}.data.dataset.phoenix14.CollateFn
  video_transform: 
        _target_: ${T}.Compose
        transforms: 
        - _target_: ${CT}.video.RandomCrop
          size: 224
        - _target_: ${CT}.video.RandomHorizontalFlip
          prob: 0.5
        - _target_: ${CT}.video.TemporalRescale
          temp_scaling: 0.2
        - _target_: ${CT}.video.FrameScale
          min: -1.
          max: 1.
        - _target_: ${CT}.video.ToTensor
          keys: [video, gloss]
    
  train_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    subset: ${data.subset}
    mode: train
    transform: ${data.video_transform}

  val_set: 
    _target_: ${csi}.data.dataset.phoenix14.MyPhoenix14Dataset
    data_root: ${phoenix14_root}
    subset: ${data.subset}
    mode: dev
    transform: ${data.video_transform}


  train_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: ${num_workers}
    pin_memory: ${pin_memory}
    shuffle: True
    dataset: ${data.train_set}
    collate_fn: ${data.collate_fn}

  val_loader:
    _target_: torch.utils.data.DataLoader
    batch_size: 2
    num_workers: ${num_workers}
    pin_memory: ${pin_memory}
    dataset: ${data.val_set}
    collate_fn: ${data.collate_fn}


